# Contents of this folder

## CDD_Annotations
Raw annotation hits generated by CDD-SPARCLE. 

## domain_identification.R 
R script used to generate csv files of domains

## Candidate_FDSIs_ENSEMBLID
Gold standard FDSIs and their best match candidate FDSI

## DomainIdentification
Full domain annotations for gold standard FDSIs and candidate FDSIs
