#Checking candidate FDSIs for shared domains with gold standard FDSIs

#loading domain annotations generated by CDD of gold standard and candidate FDSIs
columnNames <- c("Query", "Hittype",	"PSSM-ID",	"From",	"To",	"E-Value",	"Bitscore",	"Accession",	"Shortname",	"Incomplete",	"Superfamily")
FDSI_domains <- read.delim("~/R/DirectedStudies/CDD_Annotations/hitdata.txt", header = F, skip = 8, col.names = columnNames)
potential_domains <- read.delim("~/R/DirectedStudies/CDD_Annotations/hitdata3.txt", header = F, skip = 8, col.names = columnNames)

#Fix Query Names to get rid of "Q#" in front
potential_domains$Query <- str_split_fixed(potential_domains$Query, ">",2)[,2]
FDSI_domains$Query <- str_split_fixed(FDSI_domains$Query, ">",2)[,2]

#Filter for only sequences similar in sequence to gold standard FDSIs as in FDSI_Identification.R
interesting_domains <- potential_domains %>% filter(potential_domains$Query %in% FDSIsPotentialConserved30$Subject.Name)

#create a dataframe of best match candidate FDSI to each gold standard FDSI
FDSIs <- c("eIF4G1e", "eIF4G1f", "lipin-alpha","lipin-beta","B1","B2","RYR3L","RYR3S","SNAP-25a","SNAP-25b","TAp63","deltaNp63", "1A", "1E", "Cdc42E6","Cdc42E7") 
best_match <- c("ENST00000264211.12","ENST00000634879.1","ENSMUST00000129635.7","ENSMUST00000126681.7","ENSMUST00000231567.1","ENSMUST00000016771.12","ENSMUST00000021750.14",
"ENSMUST00000032813.9","ENSMUST00000028743.9","ENSMUST00000110711.8","ENSMUST00000239448.1","ENSMUST00000105644.9", "NEDD9|ENSG00000111859|ENST00000379446.10","NEDD9|ENSG00000111859|ENST00000504387.5", 
"Rac1|ENSMUSG00000001847|ENSMUST00000080537.13", "Rac2|ENSMUSG00000033220|ENSMUST00000043214.7")
Best_Potential <- data.frame(FDSIs, best_match)
write_csv(Best_Potential,"/home/fieldima/R/DirectedStudies/Candidate_FDSIs_ENSEMBLID")

#Filter for best matches
best_match_domains <- interesting_domains %>% filter(interesting_domains$Query %in% Best_Potential$best_match)

#paste domains together to form one string instead of multiple columns
best.df <- aggregate(Shortname ~ Query, data = best_match_domains, FUN = paste, collapse = ",")
best.df <- best.df %>% dplyr::rename(best_match = Query, domains = Shortname)

fdsi.df <- aggregate(Shortname ~ Query, data = FDSI_domains, FUN = paste, collapse = ",")
fdsi.df <- fdsi.df %>% dplyr::rename(FDSIs = Query)

alldomain <- inner_join(fdsi.df, Best_Potential)
alldomain <- right_join(alldomain, best.df)

#Check how many identical domain annotations between gold standard and candidate FDSIs
sum(best_match_domains$Shortname %in% FDSI_domains$Shortname)
sum(FDSI_domains$Shortname %in% best_match_domains$Shortname)

#Make table for thesis
write_csv(alldomain, "/home/fieldima/R/DirectedStudies/DomainIdentification")
